./sim bimodal 8 0 0 ./traces/gcc_trace.txt
./sim bimodal 9 0 0 ./traces/gcc_trace.txt
./sim bimodal 10 0 0 ./traces/gcc_trace.txt
./sim bimodal 11 0 0 ./traces/gcc_trace.txt
./sim bimodal 12 0 0 ./traces/gcc_trace.txt
./sim bimodal 13 0 0 ./traces/gcc_trace.txt
./sim bimodal 14 0 0 ./traces/gcc_trace.txt
./sim bimodal 15 0 0 ./traces/gcc_trace.txt
./sim bimodal 16 0 0 ./traces/gcc_trace.txt
./sim bimodal 8 0 0 ./traces/jpeg_trace.txt
./sim bimodal 9 0 0 ./traces/jpeg_trace.txt
./sim bimodal 10 0 0 ./traces/jpeg_trace.txt
./sim bimodal 11 0 0 ./traces/jpeg_trace.txt
./sim bimodal 12 0 0 ./traces/jpeg_trace.txt
./sim bimodal 13 0 0 ./traces/jpeg_trace.txt
./sim bimodal 14 0 0 ./traces/jpeg_trace.txt
./sim bimodal 15 0 0 ./traces/jpeg_trace.txt
./sim bimodal 16 0 0 ./traces/jpeg_trace.txt
./sim bimodal 8 0 0 ./traces/perl_trace.txt
./sim bimodal 9 0 0 ./traces/perl_trace.txt
./sim bimodal 10 0 0 ./traces/perl_trace.txt
./sim bimodal 11 0 0 ./traces/perl_trace.txt
./sim bimodal 12 0 0 ./traces/perl_trace.txt
./sim bimodal 13 0 0 ./traces/perl_trace.txt
./sim bimodal 14 0 0 ./traces/perl_trace.txt
./sim bimodal 15 0 0 ./traces/perl_trace.txt
./sim bimodal 16 0 0 ./traces/perl_trace.txt